name: NovaPay CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install ruff bandit pip-audit

      - name: Lint
        run: |
          ruff check app/

      - name: Unit test
        working-directory: app
        run: |
          python -m pytest -v
        
      - name: SAST
        run: |
          bandit -r app/ -x app/test_main.py
         
      - name: Dependency vulnerability scan
        run: |
          pip-audit -r app/requirements.txt

      - name: Build container image
        run: |
          docker build -t novapay-wallet:${{ github.sha }} .
          
      - name: Scan container image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'novapay-wallet:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
          ignore-unfixed: true
        
      - name: Secret scan
        if: always()
        uses: gitleaks/gitleaks-action@v2